module.exports = {
    content: ['./public/index.html', './src/**/*.{js,jsx,ts,tsx}'],
    theme: {
        extend: {
            spacing: {
                half: '50%',
                inherit: 'inherit',
                unset: 'unset',
                hero: '47rem',
                tool: '46rem',
                modalHeight: 'calc(100vh - 75px)',
                messageSidebarHeight: 'calc(100vh - 72px)',
                messageSidebarMobileHeight: 'calc(100vh - 68px)',
                formContentHeight: 'calc(100% - 20px)',
                'hero-max': 'calc(100vh - 200px)',
                'city-w': 76,
                'city-h': 84,
                'city-mobile-w': 76 * 2,
                'city-mobile-h': 84 * 2,
                'venue-w': 280,
                'venue-h': 380,
                'venue-tablet-w': 350 * 0.5,
                'venue-tablet-h': 380 * 0.5,
                'venue-mobile-w': 350 * 0.3,
                'venue-mobile-h': 380 * 0.3,
                hosthero: 'calc(100vh - 90px)',
                80: '80%',
            },
            backgroundImage: {
                hero: "url('/src/assets/images/heroBackground.jpeg')",
                tool: "url('/src/assets/images/background_img2.png')",
                vendor: "url('/src/assets/images/background_img3.jpeg')",
                modal: "url('/src/assets/images/modalBackground.png')",
                search: "url('/src/assets/images/searchCover.png')",
                hosthero: "url('/src/assets/images/hostGirl.jpg')",
                form: "url('/src/assets/images/form.png')",
            },
            transitionProperty: {
                width: 'width',
            },
            borderRadius: {
                20: 20,
            },
            fontSize: {
                20: 20,
                16: 16,
            },
            colors: {
                black: '#000000',
                white: '#ffffff',
                slate: 'rgb(226 232 240)',
                dark: '#4A3939',
                maroon: '#6F3939',
                light: '#807979',
                dim: 'rgb(199 199 199 / 10%)',
                helper: '#716B6B',
                modalDark: '#141414',
                dimWhite: '#FFFAFA',
                modalWhite: '#FFFBFB',
                socialBorder: '#00000033',
                socialText: '#5A5A5A',
                filterBorder: '#C1A1A1',
                filterBackground: '#EEEEEE',
                filterBackgroundHover: '#E1E1E1',
                searchPlaceholder: '#AAA7A7',
                sidebarBackground: '#F9F9F9',
                sidebarGreen: '#A6D997',
                sidebarMaroon: '#D98775',
                searchBackground: '#F2F2F2',
                notificationBackground: '#E0E0E0',
                peach: '#F5DDCD',
                parrot: '#D1E1BC',
                roomCard: '#D5C5E8',
                pink: '#FF9898',
                gray: '#C4C4C4',
                textBlack: '#2E2E48',
                guestTabBackground: '#F3F3F3',
                commonLight: '#F1F1F1',
                'light-maroon': '#DF7E7E',
                'light-maroon-dark': '#CE6868',
                'maroon-300': '#6F393920',
            },
            fontFamily: {
                regular: ['regular'],
                light: ['light'],
                medium: ['medium'],
                semibold: ['semibold'],
                bold: ['bold'],
                extrabold: ['extrabold'],
                mark: ['mark'],
                'roboto-regular': ['roboto-regular'],
                'roboto-bold': ['roboto-bold'],
                'inter-medium': ['inter-medium'],
                'inter-regular': ['inter-regular'],
                'inter-bold': ['inter-bold'],
                'segoe-regular': ['segoe-regular'],
            },
            maxWidth: {
                header: '23rem',
                mobile: '14rem',
            },
            lineHeight: {
                11: '58.51px',
            },
        },
        screens: {
            lg: { max: '1920px' },
            md: { max: '1200px' },
            sm: { max: '900px' },
            xs: { max: '600px' },
        },
    },

    plugins: [require('tailwindcss'), require('autoprefixer')],
}
